# Generated by Django 4.2.7 on 2024-02-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicuser",
            name="favorites",
            field=models.ManyToManyField(to="papers.paper"),
        ),
    ]
