# Generated by Django 4.2.7 on 2024-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0001_initial"),
        ("authentication", "0003_alter_basicuser_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicuser",
            name="favorites",
            field=models.ManyToManyField(blank=True, null=True, to="papers.paper"),
        ),
    ]
