# Generated by Django 4.2.7 on 2023-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0003_remove_paper_paper_id_paper_p_id"),
        ("basicuserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicuser",
            name="favorites",
            field=models.ManyToManyField(blank=True, to="baseApp.paper"),
        ),
    ]
