# Generated by Django 4.2.7 on 2023-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(blank=True, max_length=100, verbose_name="titre"),
                ),
                (
                    "resume",
                    models.CharField(
                        blank=True, max_length=50000, verbose_name="resume"
                    ),
                ),
                (
                    "auteurs",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="auteurs"
                    ),
                ),
                (
                    "institutions",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="institutions"
                    ),
                ),
                (
                    "mots_cles",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="mots cles"
                    ),
                ),
                (
                    "texte_integral",
                    models.TextField(blank=True, verbose_name="text integral"),
                ),
                (
                    "file_pdf",
                    models.FileField(
                        blank=True,
                        max_length=40000,
                        upload_to="uploads/",
                        verbose_name="file pdf",
                    ),
                ),
                (
                    "references",
                    models.CharField(
                        blank=True, max_length=20000, verbose_name="references"
                    ),
                ),
            ],
            options={
                "verbose_name": "paper",
                "verbose_name_plural": "papers",
                "get_latest_by": "date_insertion",
                "default_related_name": "paper",
            },
        ),
    ]
