# Generated by Django 4.2.7 on 2023-12-15 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paper",
            old_name="id",
            new_name="paper_id",
        ),
    ]
