# Generated by Django 4.2.7 on 2023-12-11 16:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="auteurs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100), size=None
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="institutions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100), size=None
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="mots_cles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50), size=None
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="references",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50), size=None
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="resume",
            field=models.TextField(blank=True, verbose_name="resume"),
        ),
    ]
