# Generated by Django 4.2.7 on 2023-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0002_alter_paper_auteurs_alter_paper_institutions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="date_insertion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
