# Generated by Django 4.2.7 on 2023-12-15 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0002_rename_id_paper_paper_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="paper_id",
        ),
        migrations.AddField(
            model_name="paper",
            name="p_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
