# Generated by Django 4.2.7 on 2023-12-13 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0003_paper_date_insertion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="auteurs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="file_pdf",
            field=models.FileField(
                blank=True,
                max_length=40000,
                null=True,
                upload_to="uploads/",
                verbose_name="file pdf",
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="institutions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="mots_cles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="references",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="texte_integral",
            field=models.TextField(blank=True, null=True, verbose_name="text integral"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="titre",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="titre"
            ),
        ),
    ]
