# Generated by Django 4.2.7 on 2023-12-16 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0004_customgroupadmin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomGroupAdmin",
        ),
    ]
