# Generated by Django 4.2.7 on 2023-12-13 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0007_alter_paper_auteurs_alter_paper_institutions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="auteurs",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="institutions",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="mots_cles",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="references",
        ),
    ]
