# Generated by Django 4.2.7 on 2023-12-14 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0008_remove_paper_auteurs_remove_paper_institutions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="mots_cles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
