# Generated by Django 4.2.7 on 2023-12-14 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0009_paper_mots_cles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="mots_cles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
